### ISSUE TITLE
Regarding admin user, i am not able to login as admin user to add products.

### ISSUE THREAD

**Issue by pradipkarad** [ikismail/Angular-ShoppingCart#48] opened 2019-08-08 19:30 UTC
Hey Ismail,
I am working on your existing project and i am trying to extend it. First step i am trying to make it working and trying to understand the existing functionalities and next step would be how far i can extend it i can think on it.
But initially i am able to setup the project and firebase and i am able to login with normal user but not with the admin user , basically i want to login with admin panel and add the products.
Can you please help me here , how can i make login in the app as admin user and then add the products.

**Comment by ikismail** [comment] 2019-08-09 05:04
Duplicate of #16

**Closed** 2019-08-23 16:17 UTC
