### ISSUE TITLE
Adding new user to firebase Authentication 

### ISSUE THREAD

**Issue by Babugoli** [ikismail/Angular-ShoppingCart#44] opened 2019-06-08 02:06 UTC
HI,

App is loading and working fine, But doesn't have enough guide lines to setup the DB. more of Angular person, But firebase is new. But looks straight forward here.  Its light weight and stright forward. Like it so far

1 . Creating new user, gets added to Authentication User, OAuth works fine too. But its not creating User table in Database, so that I can edit isAdmin variable. 
2. Is there Json file for DB to import. It looks like you can import Json file into firebase DB. Can you share your DB json file. if possible
3. How does structure for all the tables need to be created. 

Thanks

**Comment by pradipkarad** [comment] 2019-08-08 19:33
i also face the same issue , i can login as normal user but not as admin user and not able to add the products.
Once i can login as admin then i can add the products and then from normal user i can make and order and we can extend it to more level like saving orders ,tracking orders ,shiping and lot more.
can somebody help here in logging as admin user.

**Comment by ikismail** [comment] 2019-08-09 05:05
Duplicate of #16

**Closed** 2019-12-10 11:33 UTC
